[package]
name = "trycmd"
version = "0.1.0"
description = "Test CLI Applications."
authors = ["Ed Page <eopage@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/assert-rs/trycmd.git"
homepage = "https://github.com/assert-rs/trycmd"
documentation = "http://docs.rs/trycmd/"
readme = "README.md"
categories = ["development-tools::testing"]
keywords = ["cli", "test", "assert", "command", "duct"]
edition = "2018"
include = [
  "src/**/*",
  "Cargo.toml",
  "LICENSE-*",
  "README.md"
]

[package.metadata.release]
pre-release-replacements = [
  {file="CHANGELOG.md", search="Unreleased", replace="{{version}}", min=1},
  {file="CHANGELOG.md", search="\\.\\.\\.HEAD", replace="...{{tag_name}}", exactly=1},
  {file="CHANGELOG.md", search="ReleaseDate", replace="{{date}}", min=1},
  {file="CHANGELOG.md", search="<!-- next-header -->", replace="<!-- next-header -->\n## [Unreleased] - ReleaseDate\n", exactly=1},
  {file="CHANGELOG.md", search="<!-- next-url -->", replace="<!-- next-url -->\n[Unreleased]: https://github.com/assert-rs/trycmd/compare/{{tag_name}}...HEAD", exactly=1},
]

[features]
color = ["yansi", "concolor-control/std"]
color-auto = ["color", "concolor-control/auto"]

[[bin]]
name = "bin_fixture"

[dependencies]
wait-timeout = "0.2.0"
bstr = "0.2.14"
yansi = { version = "0.5.0", optional = true }
concolor-control = { version = "0.0.7", optional = true }

[dev-dependencies]
escargot = "0.5"
